/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bingo;
import javax.swing.JButton;
import javax.swing.GroupLayout.Alignment;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;

import bd.dbos.User;
import listener.ListenerAbreFechaTelas;
import listener.ListenerCreateUser;

import javax.swing.GroupLayout;
import javax.swing.JTextField;
import javax.swing.JPasswordField;

/**
 *
 * @author Ultron
 */
public class CadastrarPanel extends javax.swing.JFrame {
	private JTextField email;
	private JTextField nome;
	private JPasswordField passwordField;
	private JLabel resposta;
	private JButton btnCancelar;
    /**
     * Creates new form CadastrarPanel
     */
    public CadastrarPanel() {
    	setTitle("CADASTRAR");
        initComponents();
    }
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private ListenerAbreFechaTelas abreCadastrar = new ListenerAbreFechaTelas(this,"HomePanel");
    private ListenerCreateUser createUser = new ListenerCreateUser(this);
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        JButton btnCompletar = new JButton("Completar");
        
        btnCompletar.addActionListener(createUser);
        
        this.btnCancelar = new JButton("Cancelar");
        this.btnCancelar.addActionListener(abreCadastrar);
        
        JLabel lblEmail = new JLabel("Email");
        
        JLabel lblNome = new JLabel("Nome");
        
        JLabel lblSenha = new JLabel("Senha");
        
        email = new JTextField();
        email.setColumns(10);
        
        nome = new JTextField();
        nome.setColumns(10);
        
        passwordField = new JPasswordField();
        
        this.resposta = new JLabel("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(72)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(this.resposta, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addGroup(Alignment.LEADING, layout.createParallelGroup(Alignment.TRAILING, false)
        					.addComponent(lblSenha, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
        					.addComponent(lblEmail, Alignment.LEADING)
        					.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        						.addComponent(btnCompletar)
        						.addGap(57)
        						.addComponent(btnCancelar))
        					.addComponent(lblNome, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
        					.addComponent(passwordField, Alignment.LEADING)
        					.addComponent(nome, Alignment.LEADING)
        					.addComponent(email, Alignment.LEADING)))
        			.addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(28)
        			.addComponent(lblEmail)
        			.addGap(3)
        			.addComponent(email, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblNome)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(nome, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(12)
        			.addComponent(lblSenha)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(passwordField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(btnCancelar)
        				.addComponent(btnCompletar))
        			.addGap(18)
        			.addComponent(this.resposta, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarPanel().setVisible(true);
            }
        });
    }
    public User creatUser() throws Exception{
    	User user = new User(
    			this.nome.getText(),
    			this.email.getText(),
    			this.passwordField.getText()
    	);
    	return user;
    }
    public void printa(String text){
    	this.resposta.setText(text);
    }
    public void trocaNomeCancelar(){
    	this.btnCancelar.setText("Voltar para HOME");
    }

	public void bloqueiCaixas() {
		this.email.setEnabled(false);
		this.nome.setEnabled(false);
		this.passwordField.setEnabled(false);
	}

	@Override
	public String toString() {
		return "CadastrarPanel [email=" + email + ", nome=" + nome + ", passwordField=" + passwordField + ", resposta="
				+ resposta + ", btnCancelar=" + btnCancelar + ", abreCadastrar=" + abreCadastrar + ", createUser="
				+ createUser + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((abreCadastrar == null) ? 0 : abreCadastrar.hashCode());
		result = prime * result + ((btnCancelar == null) ? 0 : btnCancelar.hashCode());
		result = prime * result + ((createUser == null) ? 0 : createUser.hashCode());
		result = prime * result + ((email == null) ? 0 : email.hashCode());
		result = prime * result + ((nome == null) ? 0 : nome.hashCode());
		result = prime * result + ((passwordField == null) ? 0 : passwordField.hashCode());
		result = prime * result + ((resposta == null) ? 0 : resposta.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		CadastrarPanel other = (CadastrarPanel) obj;
		if (abreCadastrar == null) {
			if (other.abreCadastrar != null)
				return false;
		} else if (!abreCadastrar.equals(other.abreCadastrar))
			return false;
		if (btnCancelar == null) {
			if (other.btnCancelar != null)
				return false;
		} else if (!btnCancelar.equals(other.btnCancelar))
			return false;
		if (createUser == null) {
			if (other.createUser != null)
				return false;
		} else if (!createUser.equals(other.createUser))
			return false;
		if (email == null) {
			if (other.email != null)
				return false;
		} else if (!email.equals(other.email))
			return false;
		if (nome == null) {
			if (other.nome != null)
				return false;
		} else if (!nome.equals(other.nome))
			return false;
		if (passwordField == null) {
			if (other.passwordField != null)
				return false;
		} else if (!passwordField.equals(other.passwordField))
			return false;
		if (resposta == null) {
			if (other.resposta != null)
				return false;
		} else if (!resposta.equals(other.resposta))
			return false;
		return true;
	}
}